export const searchSelect = {
  id: true,
  carModel: true,
  builtYear: true,
  price: true,
  currency: true,
  color: true,
  transmission: true,
  fuelType: true,
  mileage: true,
  mileageValue: true,
  bodyType: true,
  driveType: true,
  condition: true,
  doors: true,
  seats: true,
  airConditioning: true,
  description: true,
  image: true,
  createdAt: true,
  updatedAt: true,
  carBrand: true,
  horsePower: true,
  engineType: true,
  engineDisplacement: true,
};
